Document: facturalux
Title: Debian facturalux Manual
Author: <insert document author here>
Abstract: This manual describes what facturalux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/facturalux/facturalux.sgml.gz

Format: postscript
Files: /usr/share/doc/facturalux/facturalux.ps.gz

Format: text
Files: /usr/share/doc/facturalux/facturalux.text.gz

Format: HTML
Index: /usr/share/doc/facturalux/html/index.html
Files: /usr/share/doc/facturalux/html/*.html

  
