######################################################################
# Automatically generated by qmake (1.04a) Tue Dec 10 16:10:06 2002
######################################################################

TEMPLATE = app
CONFIG -= moc
CONFIG += console
INCLUDEPATH += .
DESTDIR = $$PWD
# Input
SOURCES += main.cpp configutils.cpp
HEADERS += configutils.h
#The following line was inserted by qt3to4
QT +=  qt3support 
